[tool.poetry]
name = "shell-whiz"
version = "0.1.0"
description = "Shell Whiz: AI assistant right in your terminal"
authors = ["Tamerlan Bimzhanov <bimzhanovt.net@gmail.com>"]
readme = "README.md"
packages = [{include = "shell_whiz"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
