name: Lint Python code

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
      - .flake8
      - 'shell_whiz/**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: lint-pip-${{ hashFiles('pyproject.toml') }}

      - name: Run Black
        uses: psf/black@stable
        with:
          options: --check --diff --color --verbose
          src: shell_whiz
          version: 23.3.0

      - name: Run Flake8
        run: |
          pip install flake8==5.0.4
          flake8 --color always --verbose shell_whiz
