name: Lint

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "shell_whiz/**/*.py"
      - pyproject.toml
      - .flake8
      - poetry.lock

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Setup Poetry
        run: pip install poetry==${{ vars.POETRY_VERSION}}

      - name: Cache Poetry
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Black
        run: poetry run black --color --check --diff --verbose shell_whiz

      - name: Run Flake8
        run: poetry run flake8 --color always --verbose shell_whiz

      - name: Run isort
        run: poetry run isort --color --check --diff --verbose shell_whiz

      - name: Cache mypy
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('**/pyproject.toml') }}

      - name: Run mypy
        run: poetry run mypy -p shell_whiz
