name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  release-to-pypi:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          cache: pip

      - name: Setup Poetry
        run: pip install poetry==${{ vars.POETRY_VERSION }}

      - name: Load PyPI token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build and publish
        run: poetry publish --build
